### ISSUE TITLE
Scrapper License parse error

### ISSUE THREAD

**Issue by llazzaro** [flaskpackages/flaskpackages#21]
```
Traceback (most recent call last):
  File "/app/flask_packages/scripts/scrapper.py", line 373, in <module>
    db_connection()
  File "/app/flask_packages/scripts/scrapper.py", line 17, in db_connection
    search_packages(db)
  File "/app/flask_packages/scripts/scrapper.py", line 48, in search_packages
    add_package_to_db(package_info, name, collection)
  File "/app/flask_packages/scripts/scrapper.py", line 129, in add_package_to_db
    license = license[0]
IndexError: list index out of range
```

**Comment by llazzaro** [comment]
Not the best fix, but this will allow us to fix the broken cronjob https://github.com/flaskpackages/flaskpackages/commit/90b0a7127430a232043ccd040f8e4e97da381039
